import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



import { ChatProvider } from '@/context/ChatContext';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web 2.0 | Inicio",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  // Define el color principal de la interfaz del navegador
  themeColor: '#193cb8', // Reemplaza con tu color deseado
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
     

        <ChatProvider >
          {children}
        </ChatProvider>



      </body>
    </html>
  );
}
